matrix:
  include:

    # Backend tests
    - language: python
      python: '3.7'
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest ngpy-accounts-manager-api/

    # Frontend tests
    - language: node_js
      node_js:  '10'
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        directories:
          - ./node_modules
          - ./ngpy-accounts-manager-ui/node_modules
      install:
        - npm install
      script:
        - npm run build
        - npm run test
