# Defining the stages order
stages:
  - test
  - merge

# Excluding some branches
branches:
  except:
    - master

# Defining the jobs
jobs:
  include:

    # Backend tests
    - stage: test
      language: python
      python: '3.7'
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest ngpy-accounts-manager-api/

    # Frontend tests
    - stage: test
      language: node_js
      node_js:  '14'
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        directories:
          - ./node_modules
          - ./ngpy-accounts-manager-ui/node_modules
      install:
        - npm install
      script:
        - npm run build
        - npm run test

    # Merge to master and push
    - stage: merge
      if: (NOT type IN (pull_request)) AND (branch = develop)
      script:
        - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
        - git fetch --all || exit
        - git checkout master || exit
        - git merge --ff-only "$TRAVIS_COMMIT" || exit
        - git push https://${GITHUB_TOKEN}@github.com/egoettelmann/ngpy-accounts-manager.git || exit
