version: '3.1'

services:

  # API
  # Python backend that exposes REST controllers through Flask web server
  api:
    build:
      context: ./ngpy-accounts-manager-api
      args:
        SOURCE_VERSION: 'dev'
    entrypoint: ['/entrypoint.sh']
    ports:
      - '5000:9001'
    volumes:
      - ./ngpy-accounts-manager-api/src/app:/var/task/app:ro,delegated
    environment:
      DATABASE_URI: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/api'
      SESSION_SECRET_KEY: '${SESSION_SECRET_KEY}'
      CORS_ORIGIN: '${FRONTEND_URI}'
      WAIT_HOSTS: db:5432

  # UI
  # Nginx that serves static assets (and proxies '/api' requests to API for CORS).
  ui:
    build:
      context: ./ngpy-accounts-manager-ui
      args:
        PROD_BACKEND_URI: '${BACKEND_URI}'
    restart: always
    ports:
      - '4200:80'
    volumes:
      - ./ngpy-accounts-manager-ui/dist/ngpy-accounts-manager-ui:/usr/share/nginx/html
    environment:
      NGINX_PROFILE: 'dev'

  # Database
  # Postgres database
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./database/samples:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
