version: '3.1'

services:

  # API
  api:
    build: ./ngpy-accounts-manager-api
    restart: always
    ports:
      - 5050:5050
    volumes:
    - ./ngpy-accounts-manager-api/src/app:/var/task/app:ro,delegated
    environment:
      DATABASE_URI: postgresql://api:password@db:5432/api
      SESSION_SECRET_KEY: abcdef

  # Database
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password

  # UI
  ui:
    build: ./ngpy-accounts-manager-ui
    restart: always
    ports:
      - 4200:80
