version: 2.1

# Defining parameters
parameters:
  docker-image-api:
    type: string
    default: "cimg/python:3.7"
  docker-image-ui:
    type: string
    default: "cimg/node:14.19"

jobs:
  # Build the API
  build-api:
    working_directory: ~/ngpy-accounts-manager/ngpy-accounts-manager-api
    docker:
      - image: << pipeline.parameters.docker-image-api >>
    steps:
      - checkout:
          path: ~/ngpy-accounts-manager
      - restore_cache:
          keys:
            - pip-{{ checksum "requirements.txt" }}
            - pip-
      - run:
          name: "Get dependencies"
          command: pip install -r requirements.txt -t ./src/site-packages
      - save_cache:
          paths:
            - ./src/site-packages
          key: pip-{{ checksum "requirements.txt" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./src
            - ./tests

  # Test the API
  test-api:
    working_directory: ~/ngpy-accounts-manager/ngpy-accounts-manager-api
    docker:
      - image: << pipeline.parameters.docker-image-api >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Test"
          command: PYTHONPATH=./src/site-packages:./src python -m pytest tests/
      - persist_to_workspace:
          root: .
          paths:
            - ./src

  # Build the UI
  build-ui:
    working_directory: ~/ngpy-accounts-manager/ngpy-accounts-manager-ui
    docker:
      - image: << pipeline.parameters.docker-image-ui >>
    steps:
      - checkout:
          path: ~/ngpy-accounts-manager
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: "Get dependencies"
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: "Build"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Test the UI
  test-ui:
    working_directory: ~/ngpy-accounts-manager/ngpy-accounts-manager-ui
    docker:
      - image: << pipeline.parameters.docker-image-ui >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Test"
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/ngpy-accounts-manager-ui

workflows:
  # The main workflow
  build-and-test:
    jobs:
      # API: build and test
      - build-api:
          filters:
            branches:
              only: /.*/
      - test-api:
          requires:
            - build-api
          filters:
            branches:
              only: /.*/
      # UI: build and test
      - build-ui:
          filters:
            branches:
              only: /.*/
      - test-ui:
          requires:
            - build-ui
          filters:
            branches:
              only: /.*/
